{
  "tests/integration/secretsmanager/test_secretsmanager.py::TestSecretsManager::test_can_recreate_delete_secret": {
    "recorded-date": "03-08-2022, 14:27:54",
    "recorded-content": {
      "create_secret_res_0": {
        "ARN": "arn:aws:secretsmanager:<region>:111111111111:secret:<SecretId-0idx><ArnPart-0idx>",
        "Name": "<SecretId-0idx>",
        "VersionId": "<uuid:1>"
      },
      "delete_res_1": {
        "ARN": "arn:aws:secretsmanager:<region>:111111111111:secret:<SecretId-0idx><ArnPart-0idx>",
        "Name": "<SecretId-0idx>",
        "DeletionDate": "datetime"
      },
      "create_secret_res_1": {
        "ARN": "arn:aws:secretsmanager:<region>:111111111111:secret:<SecretId-0idx><ArnPart-1idx>",
        "Name": "<SecretId-0idx>",
        "VersionId": "<uuid:2>"
      }
    }
  },
  "tests/integration/secretsmanager/test_secretsmanager.py::TestSecretsManager::test_exp_raised_on_creation_of_secret_scheduled_for_deletion": {
    "recorded-date": "03-08-2022, 14:47:19",
    "recorded-content": {
      "delete_res": {
        "ARN": "arn:aws:secretsmanager:<region>:111111111111:secret:<SecretId-0idx><ArnPart-0idx>",
        "Name": "<SecretId-0idx>",
        "DeletionDate": "datetime"
      },
      "invalid_req_ex": {
        "typename": "InvalidRequestException",
        "message": "An error occurred (InvalidRequestException) when calling the CreateSecret operation: You can't create this secret because a secret with this name is already scheduled for deletion."
      }
    }
  }
}